name: Agenda CI

on:
  push:
    branches: ["main"]

env:
  USER_NAME: Diana

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Compilar
        run: mvn compile
        working-directory: demo

      - name: Ejecutar pruebas
        run: mvn clean test
        working-directory: demo
