name: Agenda CI

on:
  push:
    branches: [ "main" ]

env:
  STUDENT_NAME: Diana

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Compilar
        run: mvn compile

      - name: Ejecutar pruebas
        run: mvn -f demo/pom.xml clean test
